/**
 * URL Builder for Lovable Link Generator
 * Constructs hybrid URLs combining referral links with Build with URL parameters
 */

export interface BuildURLOptions {
  prompt: string;
  images?: string[];
  referralId: string;
  autosubmit?: boolean;
}

export interface GeneratedURL {
  full: string;
  base: string;
  query: string;
  fragment: string;
}

/**
 * Encodes a prompt string for safe URL transmission
 * Handles special characters and long prompts (up to 50k chars)
 */
export function encodePrompt(prompt: string): string {
  return encodeURIComponent(prompt);
}

/**
 * Validates image URLs for Lovable compatibility
 * - Must be publicly accessible
 * - Supported formats: JPEG, PNG, WebP
 * - Maximum 10 images
 */
export function validateImageUrls(urls: string[]): { valid: string[]; errors: string[] } {
  const errors: string[] = [];
  const valid: string[] = [];
  const supportedFormats = ['jpg', 'jpeg', 'png', 'webp'];

  if (urls.length > 10) {
    errors.push(`Maximum 10 images allowed. You provided ${urls.length}.`);
    return { valid: urls.slice(0, 10), errors };
  }

  urls.forEach((url, index) => {
    try {
      new URL(url);
      const extension = url.split('.').pop()?.toLowerCase() || '';
      if (!supportedFormats.includes(extension)) {
        errors.push(`Image ${index + 1}: Unsupported format. Use JPEG, PNG, or WebP.`);
      } else {
        valid.push(url);
      }
    } catch {
      errors.push(`Image ${index + 1}: Invalid URL format.`);
    }
  });

  return { valid, errors };
}

/**
 * Builds a complete Lovable Build with URL hybrid link
 * Combines referral tracking with automatic app generation
 *
 * Structure: https://lovable.dev/?via=ID&autosubmit=true#prompt=ENCODED_PROMPT&images=URL1&images=URL2
 */
export function buildLovableURL(options: BuildURLOptions): GeneratedURL {
  const { prompt, images = [], referralId, autosubmit = true } = options;

  // Validate inputs
  if (!prompt.trim()) {
    throw new Error('Prompt cannot be empty');
  }

  if (prompt.length > 50000) {
    throw new Error('Prompt exceeds maximum length of 50,000 characters');
  }

  if (!referralId.trim()) {
    throw new Error('Referral ID is required');
  }

  // Build base URL
  const base = 'https://lovable.dev/';

  // Build query string (server-side processing)
  const queryParams = new URLSearchParams();
  queryParams.append('via', referralId);
  if (autosubmit) {
    queryParams.append('autosubmit', 'true');
  }
  const query = `?${queryParams.toString()}`;

  // Build fragment (client-side processing)
  const fragmentParams = new URLSearchParams();
  fragmentParams.append('prompt', prompt);

  // Add images to fragment
  images.forEach((imageUrl) => {
    fragmentParams.append('images', imageUrl);
  });

  const fragment = `#${fragmentParams.toString()}`;

  // Combine all parts
  const full = base + query + fragment;

  // Validate URL length (browser limit is typically 2048-8192 chars)
  if (full.length > 2048) {
    console.warn(
      `Generated URL is ${full.length} characters long. Some browsers may truncate URLs over 2048 characters.`
    );
  }

  return { full, base, query, fragment };
}

/**
 * Copies a URL to clipboard and returns success status
 */
export async function copyToClipboard(text: string): Promise<boolean> {
  try {
    if (navigator.clipboard && window.isSecureContext) {
      await navigator.clipboard.writeText(text);
      return true;
    } else {
      // Fallback for older browsers or non-secure contexts
      const textArea = document.createElement('textarea');
      textArea.value = text;
      textArea.style.position = 'fixed';
      textArea.style.left = '-999999px';
      document.body.appendChild(textArea);
      textArea.select();
      const success = document.execCommand('copy');
      document.body.removeChild(textArea);
      return success;
    }
  } catch (error) {
    console.error('Failed to copy to clipboard:', error);
    return false;
  }
}

/**
 * Generates a shareable link preview text
 */
export function generatePreviewText(prompt: string, referralId: string): string {
  const truncatedPrompt = prompt.length > 100 ? prompt.substring(0, 100) + '...' : prompt;
  return `🔗 Lovable App Generator\n\n"${truncatedPrompt}"\n\nGenerated by: ${referralId}`;
}

/**
 * Extracts parameters from a generated URL for display/editing
 */
export function parseGeneratedURL(url: string): Partial<BuildURLOptions> | null {
  try {
    const urlObj = new URL(url);
    const referralId = urlObj.searchParams.get('via') || '';
    const autosubmit = urlObj.searchParams.get('autosubmit') === 'true';

    // Parse fragment (client-side params)
    const fragment = urlObj.hash.substring(1);
    const fragmentParams = new URLSearchParams(fragment);
    const prompt = fragmentParams.get('prompt') || '';
    const images = fragmentParams.getAll('images');

    return {
      prompt,
      images: images.length > 0 ? images : undefined,
      referralId,
      autosubmit,
    };
  } catch {
    return null;
  }
}
